# configuration for https://ohi-science.shinyapps.io/esp_app
study_area:       Spain
git_owner:        OHI-Science
git_repo:         esp
git_slug:         OHI-Science/esp
git_url:          https://github.com/OHI-Science/esp
app_url:          https://ohi-science.shinyapps.io/esp_app
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2014-11-25
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: e1defd965ddbdd884893608a25a0b5dd0a1aedd2

tabs_hide:        
- Calculate
- Report

